rap2hpoutre/laravel-log-viewer

- src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
@rap2hpoutre requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/rap2hpoutre/laravel-log-viewer/
> Scrutinizer Auto-Fixes

- src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
Returns empty array if there are no log files
> Fix exception undefined offsed 0 - issue#14

- src/controllers/LogViewerController.php
The code has been slightly refactored in order to avoids a crash in environments that have no Alias definitions.
> Remove dependency on Alias definitions

- README.md
> Change to ::class notation

- src/controllers/LogViewerController.php
I had an error when using Laravel 5.2 and Laravel Collective and using Input.
With `request()->has()` it should work for every version as well.
> Use request instead of Input to make it more consistent

- README.md
- src/controllers/LogViewerController.php
A few things were missing:
- Namespacing in the route defintion
- Provider registration in bootstrap.php
- Loading Lumen controller
Display is working, but download and delete still need to be fixed
> Add Lumen support

- README.md
- src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
- src/controllers/LogViewerController.php
This changes will remove facade dependency from the package as some people want to keep facades disabled in lumen :)
> Remove facade dependency

- src/controllers/LogViewerController.php
- src/views/log.blade.php
Proposed changes:
- Add a "delete all files" option on the right side next to "Delete file".
- Only show the download & delete links when possible.
Why:
Faster to delete all the files, keep it clean.
> Add 'delete all files' option & only show download/delete links when possible

- src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
Based on #94 I've made fix that would only show .log files in the menu.
> Display .log files only in sidebar

- src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
Add option to have timestamps on logs.
> Add timezone to logs

- composer.json
So people can get this package in packagist.org by searching with type field.
> Add type key

- src/views/log.blade.php
> Fix long log file names breaking their container

- src/controllers/LogViewerController.php
Using this fix for a project where I don't use laravel views at all. Thought it could prove useful for someone.
> Add API compability

- src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
> Xembill patch 1

- src/views/log.blade.php
> Fix default sorting order

- src/controllers/LogViewerController.php
- src/views/log.blade.php
Add function cleans file without deleting, helps when there are problems with access to the log file created in the background.
> Clean log file without deleting

- src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
- src/controllers/LogViewerController.php
- src/views/log.blade.php
Hello,
If you have subfolders on log folder for different log channels, this modification may read all subfolders of logs folder.
Thank you,
> Be able display subfolders of log folder.

- src/controllers/LogViewerController.php
- src/views/log.blade.php
Hello,
Fix #157 
Use encrypt helper method in log view.
Thanks.
> Fix download, clean, delete functions when selected subfolders

- src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
- src/Rap2hpoutre/LaravelLogViewer/Pattern.php
This allows if in the feature we want to create a new featured that include patterns we cant add this for the best readability (some patterns get really complicated)
> Creating a  array that content  all the "pattern" for the preg_match_all and preg_match 

- src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
- src/Rap2hpoutre/LaravelLogViewer/Pattern.php
- src/config/logviewer.php
- src/views/log.blade.php
> Log Location customisable #139

- README.md
Lumen new version use $router instead of $app
> Support $router for Lumen

- src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
- src/views/log.blade.php
I delete all previews branches for this, to make more clear, sorry for all the mess
@rap2hpoutre I hope that you like it! 
https://github.com/rap2hpoutre/laravel-log-viewer/issues/162
> Clear PR for Multiple Log View Locations #162

- src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
@rap2hpoutre Please review this function (step by step) I think this is the right way.
> Fixing if ->storage_path is array and have Multiple Log View Locations folders

- src/controllers/LogViewerController.php
By making the location of the view a variable, users can move it to a custom location, eg. when using different modules in their application.
> Make view path a variable

- README.md
- composer.json
- src/controllers/BaseController.php
- src/controllers/LogViewerController.php
> Fixing PSR-0 autoload issue

- src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
https://github.com/rap2hpoutre/laravel-log-viewer/issues/263
> Fix left hand file name sorting

- README.md
Include Laravel 9 in the list of supported Laravel supported versions
> Mention Laravel 9 in supported versions

- composer.json
> Larvel 10 Support
