src/controllers/LogViewerController.php, src/views/log.blade.php
This fixes issue with url pointing to wrong base path when app is installed in e.g. `localhost/my-app/public/`
Also simplified usage of encoding filenames, no need to encrypt it.
=> Fix url to file and simplified encoding of filename

README.md, src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewerServiceProvider.php, src/controllers/LogViewerController.php
This fixes issue #9 by allowing both laravel 5 and laravel 4.2 to have overidden views.
=> Added overridable views for both Laravel 5 and Laravel 4.2

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
Upon installing in Laravel 4.2, the log viewer threw an exception because one line failed to populate the $current array from the regex. These changes allow it to keep going when this happens and render the page properly.
=> Adding error handling for instances where regex does not find required elements

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
If storage/logs had directories in it, exceptions were being thrown. This just filters out directories so they don't display on the sidebar at all.
=> Filter out any directories within the logs folder.

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
In the [documentation](http://laravel.com/docs/5.1/errors#configuration) there's not only options for storing log files inside the app as `single` and `daily`, but options for storing errors to system logs: `syslog` and `errorlog`.
In my case `errorlog` is used. So all errors from Laravel are saved to `/var/logs/nginx/<project-name>-error.log`
In order to have ability to read that log I should make my custom controller with one line which specify path to my errorlog:
LaravelLogViewer::setFile('/var/log/nginx/<project-name>-error.log');
This PR allows to set absolute and relative log files as well.
=> Add ability to add log files with absolute path.

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php, src/controllers/LogViewerController.php, src/views/log.blade.php
The path given as query parameters aren't validated. To prevent accessing files outside of the log directory this patch validates the file names.
I've fixed this mainly to avoid something like: http.../logs?dl=Li4vLi4vLmVudg==
=> validate log file path

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
This PR recovers using log files with absolute path, e.g. 
```php
LaravelLogViewer::setFile('/var/log/nginx/<project-name>-error.log');
```
This was working after merging https://github.com/rap2hpoutre/laravel-log-viewer/pull/47, but broken in https://github.com/rap2hpoutre/laravel-log-viewer/commit/44f7fbb13eabc0d1571455b3e68a812a617c3691
=> Fix using log files with absolute path

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php, src/views/log.blade.php
Hopefully I've done this in a manner you would agree with; I thought about using a second preg_match to get the context since that wouldn't disrupt the $current variable IDs, but this seems cleaner than that.
I've tested this locally in my setup and things seem to work out as I would expect. Let me know if you'd like me to make adjustments so that this can be merged in.
=> Add Log context to table

README.md
In the latest version of Laravel, web routes now lives in `app/routes/web.php`. 
This proposed change makes the reference to the routes location generic, so it could apply to both the latest versions of Laravel or what it is in Laravel 5.1 (LTS) (`app/Http/routes.php`).
=> Make routes location generic

src/controllers/LogViewerController.php
Solves #75
`Class redirect does not exist` error when deleting a log file.
The problem is caused because:
> Since version 5.2, Lumen uses a different Redirector class (other than Illuminate's) and no longer offers a container alias for the Redirector class or the Redirect Facade out of the box.
I've implemented your suggestion
> Maybe we should use redirect() if it exists and Redirect facade if not?
Tested with a fresh installation of 
- Laravel versions 4.2 and 5.3. 
- Lumen versions 5.1, 5.2, and 5.3.
=> Use "redirect" helper function to support Lumen's Redirector.

README.md, src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewerServiceProvider.php
Added ability to publish log.blade.php into `/resources/views/vendor/laravel-log-viewer/` and updated readme accordingly.
```
php artisan vendor:publish --provider="Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider" --tag=views
```
=> Added ability to publish log.blade.php

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
As requested in #86 I've made some changes in the regex to support the queue log file .
Other changes:
- Added simple docblock
- Replaced getLogLevels() with an array because 'processed' isn't really a log level.
=> Regex update for Queue worker logs

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
Proper check the file parameter to disallow arbitrary file downloads. Didn't I fix this issue already a while ago?
=> fix pathToLogFile to only get files in log dir

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php, src/views/log.blade.php
To address issue #120 ... This will update the log-viewer package to work with new Bootstrap 4. Changes include:
- updates to meta tags according to BS4 template
- replacing all glyphicons from BS3 with FontAwesome icons
- replacing datatables with new version that supports BS4
- small changes to layout for new BS4 column syntax
- changes to button that expands each row for BS4 styling and semantics
- updated jQuery for BS4
In addition to the stock changes to get BS4 working, I also propose some more CSS overrides to make the default layout more readable. BS4 uses rem = 16px as their base font size, as opposed to BS3 (14px), so things are larger by default. I added overrides for:
- `.sidebar` - smaller font, smaller line height, extra spacing at bottom for small viewport)
- entire …
=> Update for Bootstrap 4 

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewerServiceProvider.php
Fixes #126
Lumen does not have a `config_path` helper, so we have to make our own. Thanks to https://gist.github.com/mabasic/21d13eab12462e596120#gistcomment-2140273 for the correct method to get the config path for Lumen.
=> Fix config_path issue

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
Added ability to use GLOB_BRACE flag when using the glob() function for the LOGVIEWER_PATTERN.
Useful when using delaycompress in logrotate and not using daily, for example in the logs folder having:
- laravel.log
- laravel.log.1
- laravel.log.2.gz
I can now ignore the gzip file and include the others using this pattern:
- LOGVIEWER_PATTERN=*.{log,log.1}
=> Adding GLOB_BRACE pattern detection

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php, src/controllers/LogViewerController.php, src/views/log.blade.php
This fixes #144.
Any non-standard format log files will be displayed as a two column table including line number and content.
=> Read non-standard log format

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
$this->storage_path expected to be a string, not an array
Current folder is not being set, so that $current_folder var in blade template is empty even when a folder is currently selected.
=> fix setFolder method

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php, src/config/logviewer.php
I'm using this package to view the access log generated by [spatie/laravel-http-logger](https://github.com/spatie/laravel-http-logger) The file size is easily growing. 
After few Mb, the page is not able to render any more.
I think the number of Mb should be the choice of the developer. In my case, I don't need more than 2Mb before I need to download it.
=> Add MAX_FILE_SIZE to config

src/controllers/LogViewerController.php
PHP 7.4 throws an error while trying to access array offset on value
of type bool returned by reset() method for empty log
=> Handle empty log array while preparing data to display

README.md
A group (a.k.a. tag) should be added in publishing declaration (src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewerServiceProvider.php line 34) to make this clearer.
=> Added configuration publishing directions

src/views/log.blade.php
This adds a simple darkmode css for the log template. 
Uses JS to toggle darkmode on/off and saves users setting to localstorage. 
If anyone wants to improve this go ahead, but as for now, it seems like it would do the job. 
Referencing #213
=> Added toggle for darkmode with simple darkmode css

src/views/log.blade.php
`word-wrap: break-word` is not respected inside the `.list-group-item`. 
Hence `word-break: break-word` is used to allow overriding.
=> Fix for broken layout issue in #228

src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php
In case log file is not readable (generated by some other process, cron etc) exception is thrown.
This PR checks for that and returns message about it as log content.
Thoughts on what would be the best way to make it clear it is an error message from package and not actual log file content?
It would also be possible to mark files as unreadable in file list but that requires checking all files at every load and might not be advisable. Thoughts?
=> Exception thrown if file is not readable

.travis.yml, README.md, src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php, src/controllers/LogViewerController.php, src/views/log.blade.php, tests/LaravelLogViewerTest.php
In response to issue #202 where the package doesn't detect other log files deep in the year and month folders. I modified the package to generate an array of the directory structure with the files therein so user can click on any file to view logs.
=> support for laravel daily logs
